### ISSUE TITLE
当前登录用户的信息如何添加

### ISSUE THREAD

**Issue by java1c** [jeecgboot/jeecg-boot-starter#16]
LoginUser sysUser = (LoginUser) c; 在后端使用这个方法进行获取当前登录用户的信息，我再loginuser里面添加了一个新的字段major，我应该如何将用户的major字段信息注入到loginuser中，使我可以在SecurityUtils.getSubject().getPrincipal()方法中获取到这个用户信息

**Comment by zhangdaiscott** [comment]
jwt底层逻辑改造
