### ISSUE TITLE
添加一个chat-gpt快速集成的Starter

### ISSUE THREAD

**Issue by liuliuzo** [jeecgboot/jeecg-boot-starter#4]
申请提交一个chat-gpt快速集成的starter

@adming-zz

**Comment by zhangdaiscott** [comment]
留个联系QQ，先做下沟通

**Comment by liuliuzo** [comment]
@zhangdaiscott 你好，我QQ:165348097  微信:liuliuzo
事情是这样的，我有个项目用到了你们的框架，然后项目集成了chat-gpt， 现在想贡献一个chat-gpt的starter给你们，里面包含一个chat-gpt client和请求响应的封装
